# Generated by Django 5.0.4 on 2024-05-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='super_description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Подробное описание'),
        ),
    ]
